### ISSUE TITLE
Complex conditions

### ISSUE THREAD

**Issue by Sn3b** [danielpalme/GenericSearch#6]
Do you think it would be possible to modify the logic to allow complex conditions? By complex I mean something like (stupid example):

``` SQL
WHERE (Email like '%test%' AND BrithDate < 01/01/1980)
   OR (Email like '%anothertest%' AND BirthDate > 01/01/1980)

```

**Comment by danielpalme** [comment]
That's possible, but probably not an easy task.
You would have to change quite a lot to support that scenario.

Adding support for OR instead of only AND should be quite easy.
The UI would require an extra operator selection (e.g. a dropdown where you can select AND or OR).
This has to passed to the _AbstractSearch_ criteria and you have to modify the [Combine](https://github.com/danielpalme/GenericSearch/blob/master/GenericSearch.Core/AbstractSearch.cs#L73)-method.

Adding custom precedence support would require much more effort.
The UI has to be recreated completely, since you need an ability to add brackets at arbitrary positions to your query.
This query has to be parsed and interpreted on the server side.

**Comment by Sn3b** [comment]
I see...

I was thinking more of returning the predicates in `AbstractSearch.ApplyToQuery` (maybe even rename it) and then use [PredicateBuilder ](http://www.albahari.com/nutshell/predicatebuilder.aspx) in `FilteringExtensions.ApplyFilteringCriteria` to combine the predicates returned.

What do you think?

**Comment by danielpalme** [comment]
Well the tasks/problem stays the same, no matter which refactorings you make.
You still have to change the UI and the server side code accordingly. See my [comment](https://github.com/danielpalme/GenericSearch/issues/6#issuecomment-247768547) above.
